caffe2/caffe2/binaries/core_overhead_benchmark.cc: avoid shadowing warnings
Summary:
Fix warnings exposed by gcc-4.9.x's -Wshadow-compatible-local
I plan to enable this for all of fbcode, soon.
See t13698406 for justification.

Remove declaration of unused outer "stream".

This avoids the following errors:

  caffe2/caffe2/binaries/core_overhead_benchmark.cc:28:27: error: declaration of 'stream' shadows a previous local [-Werror=shadow-compatible-local]
  caffe2/caffe2/binaries/core_overhead_benchmark.cc:26:25: error: shadowed declaration is here [-Werror=shadow-compatible-local]

Reviewed By: Yangqing

Differential Revision: D4544811

fbshipit-source-id: c94e8a6e6d59705c86bc654f05d4de1ae4213eac