Fix compilation error: load_fp32_from_fp16’ was not declared in this scope for ppc64le (#120307)
This patch adds missing Implementation of load_fp32_from_fp16 for half. Fixes the error  load_fp32_from_fp16’ was not declared in this scope .

Pull Request resolved: https://github.com/pytorch/pytorch/pull/120307
Approved by: https://github.com/jgong5